### ISSUE TITLE
link_to_function in the helper is deprecated in Rails 4.

### ISSUE THREAD

**Issue by emilkarl** [runtimerevolution/survey#22]
undefined method `link_to_function' for #<#<Class:0x007ff02f4b5470>:0x007ff02f4ad900>

**Comment by albertpak** [comment]
Ran into this issue today...any solution for this yet?

**Comment by alex-quiterio** [comment]
Hi @emilkarl and @albertpak 

We'll fix the issue soon. Thank you for reporting the problem.

**Comment by alex-quiterio** [comment]
Hi @emilkarl and @albertpak 

The problem is fixed.

Cheers!

**Comment by yuvasoft** [comment]
i upgrade application rails 3 to rails 4. in my application lots of place use link_to_function. but now present time i have upgraded my app. but i got link_to_function error how to resloved it.
undefined method `link_to_function' for #<#<Class:0xceb6e94>:0xe000844>
